#### Required content ----
# Absolute path to Seurat object
INPUT: /home/duansq/pipeline/scrna-seq/resources/test_data.rds
# Grouping information, ensure that the grouping field exists in the meta.data of the Seurat object, and only contains two groups
GROUP: METTL3_group
# Set the positive group you want to use for comparison
TREATMENT: positive
# Differentially expressed gene analysis method (optional: MAST, bimod, wilcox, LR, t)
TEST_METHOD: wilcox
# Set up the assay for analysis, usually RNA
ASSAY: RNA
# Set your species (optional: Homo sapiens or Mus musculus)
SPECIES: Homo sapiens
#### Software settings ----
# pyscenic path
PYSCENIC_PATH: /opt/pySCENIC/0.11.2/bin/pyscenic
# The path of python where pyscenic is located
PYTHON_PATH: /opt/pySCENIC/0.11.2/venv/bin/python
# pyscenic annotation file. Download from https://pyscenic.readthedocs.io/en/latest/installation.html#auxiliary-datasets
ANNOTATIONS_FILE_PATH: /DATA/public/cisTarget_databases/human/motifs-v9-nr.hgnc-m0.001-o0.0.tbl 
# pyscenic database. Download from https://resources.aertslab.org/cistarget/
DATABASE_FILE_PATH: 
  /DATA/public/cisTarget_databases/human/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather
  /DATA/public/cisTarget_databases/human/hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather
# A list of transcription factors. Download from https://github.com/aertslab/pySCENIC/tree/master/resources
TF_LIST: /DATA/public/cisTarget_databases/resources/hs_hgnc_tfs.txt
#### Optional ---- 
# Selected p-value and log2(fold change) threshold when performing differentially expressed gene analysis
P_VALUE: 0.05
LOG2FC: 0.25