#### 必须填写的内容 ----
# 从R语言里面保存的Seurat对象路径
INPUT: /home/duansq/pipeline/scrna-seq/resources/test_data.rds
# 分组信息，保证分组字段在Seurat对象的meta.data存在，并且只包含两组
GROUP: METTL3_group
# 设置分组里的试验组
TREATMENT: positive
# 差异检测方法（可选：MAST，bimod，wilcox，LR，t）
TEST_METHOD: wilcox
# 设置Assay
ASSAY: RNA
# 设置物种（可选：Homo sapiens或者Mus musculus）
SPECIES: "Homo sapiens"
#### 软件设置 ----
# pyscenic路径
PYSCENIC_PATH: /opt/pySCENIC/0.11.2/bin/pyscenic
# 安装pyscenic的python路径
PYTHON_PATH: /opt/pySCENIC/0.11.2/venv/bin/python
# pyscenic注释文件
ANNOTATIONS_FILE_PATH: /DATA/public/cisTarget_databases/human/motifs-v9-nr.hgnc-m0.001-o0.0.tbl 
# 基因组排序文件
DATABASE_FILE_PATH: 
  /DATA/public/cisTarget_databases/human/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather
  /DATA/public/cisTarget_databases/human/hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather
#### 可以选择性更改 ---- 
# 阈值
P_VALUE: 0.05
LOG2FC: 0.25